#====================================
#       変数
#====================================
### dotnet run
# @baseUrl = http://localhost:5135

### デバッグ実行
@baseUrl = http://localhost:5002

#====================================
# Customer
#====================================

### GET List
GET {{baseUrl}}/api/v1/customer
Accept: application/json

### GET List
GET {{baseUrl}}/api/v1.1/customer
Accept: application/json