#====================================
#       変数
#====================================
### dotnet run
# @baseUrl = http://localhost:5135

### デバッグ実行
@baseUrl = http://localhost:5002/api/v1

#====================================
# Customer
#====================================

### GET List
GET {{baseUrl}}/customer
Accept: application/json

### GET Detail
GET {{baseUrl}}/customer/1
Accept: application/json

### POST
POST {{baseUrl}}/customer
content-type: application/json

{
  "name": "顧客ABC",
  "productKey": "S1TMBL5zKMUbx38A",
  "LicenseLimit": 10
}

### PUT
PUT {{baseUrl}}/customer/2
content-type: application/json

{
  "name": "顧客EFG",
  "productKey": "yHtOQX6IAAf46JkB",
  "LicenseLimit": 20
}

### DELETE
DELETE {{baseUrl}}/customer/6